openapi: 3.0.3
info:
  title: NextGen DAS | Descriptions API
  description: >-
    <p><h2>Archival Descriptions hierarchical grouping:</h2></p>
    <img src="https://i.imgur.com/vVcfhig.png"/>
    
  version: 2.0.0
  termsOfService: https://www.archives.gov/social-media/terms-of-service.html
  contact:
    name: O&M
    url: https://www.archives.gov/faqs
    email: api@nara.gov
servers:
  - url: https://stage.das.nara.gov/api/v2
    description: Staging server
  - url: https://dev.das.nara.gov/api/v2
    description: Dev server
  - url: http://localhost:4010
    description: Local Prism server
tags:
  - name: Descriptions
    description: All operations that relate to DAS archival descriptions
paths:
  /record-groups:
    get:
      security:
        - jwt: []
      operationId: getRecordGroups
      tags:
        - Descriptions
      description: Returns a page of Record Groups
      responses:
        '200':
          headers:
            X-Total-Count:
              schema:
                type: integer
              description: Total number of items. Non-negative number.
            X-Total-Pages:
              schema:
                type: integer
              description: Total number of pages. Non-negative number.  
          content:
            application/json:
              schema:
                $ref: models/GetRecordGroupsResponse.yaml
              examples:
                mandatoryPropertiesOnly:
                  $ref: examples/record-groups/RecordGroupsPage.yaml
          description: >-
            A page of Record Groups    
    post:
      description: Creates several <a href="https://www.archives.gov/research/alic/tools/record-group-clusters.html">Record Groups</a>
      security: 
        - jwt: []
      requestBody:
        $ref: '#/components/requestBodies/PostRecordGroupsRequest'
      responses:
        '207':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MultiStatusResponse'
              examples:
                bothRecordsSaved:
                  $ref: '#/components/examples/RecordGroupsCreatedOk'
                oneRecordOutOfTwoFailed:
                  $ref: '#/components/examples/RecordGroupsCreatedPartialSuccess'
                singleRecordGroupSaved:
                  $ref: '#/components/examples/SingleRecordGroupSaved'
                singleRecordGroupRejected:
                  $ref: '#/components/examples/SingleRecordGroupRejected'
          description: >-
            Multi-status response with the list of statuses for each requested entity.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Problem'
          description: >
            Error response for cases when the backend rejects the attempt to add a new visit intention.
      operationId: createRecordGroups
      tags:
        - Descriptions

  /record-groups/{naid}:
    get:
      security:
        - jwt: []
      operationId: getRecordGroupByNaid
      tags:
        - Descriptions
      description: Returns a single Record Group
      parameters:
        - in: path
          name: naid
          schema:
            type: integer
          required: true
          description: Record Group NAID
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: 'models/RecordGroup.yaml'
              examples:
                mandatoryPropertiesOnly:
                  $ref: examples/record-groups/mandatoryPropertiesOnly.yaml
          description: >-
            A single Record Group
  
  /collections:
    get:
      security:
        - jwt: []
      operationId: getCollections
      tags:
        - Descriptions
      description: Returns a page of Collections
      responses:
        '200':
          headers:
            X-Total-Count:
              schema:
                type: integer
              description: Total number of items. Non-negative number.
            X-Total-Pages:
              schema:
                type: integer
              description: Total number of pages. Non-negative number.  
          content:
            application/json:
              schema:
                $ref: models/GetCollectionsResponse.yaml
          description: >-
            A page of Collections
    post:
      description: Creates several Collections
      security: 
        - jwt: []
      requestBody:
        $ref: '#/components/requestBodies/PostCollectionsRequest'
      responses:
        '207':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MultiStatusResponse'
              examples:
                allOk:
                  $ref: '#/components/examples/RecordGroupsCreatedOk'
                partialSuccess:
                  $ref: '#/components/examples/RecordGroupsCreatedPartialSuccess'
          description: >-
            Multi-status response with the list of statuses for each requested entity.
      operationId: createCollections
      tags:
        - Descriptions
  /collections/{naid}:
    get:
      security:
        - jwt: []
      operationId: getCollectionByNaid
      tags:
        - Descriptions
      description: Returns a single Collection
      parameters:
        - in: path
          name: naid
          schema:
            type: integer
          required: true
          description: Collection NAID
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: models/Collection.yaml
              examples:
                mandatoryPropertiesOnly:
                  $ref: '#/components/examples/SingleCollection'
          description: >-
            A single Collection

  /series:
    post:
      description: Creates several Series descriptions
      security: 
        - jwt: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/PostSeriesRequest'
      responses:
        '207':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MultiStatusResponse'
              examples:
                bothRecordsSaved:
                  $ref: '#/components/examples/RecordGroupsCreatedOk'
                oneRecordOutOfTwoFailed:
                  $ref: '#/components/examples/RecordGroupsCreatedPartialSuccess'
                singleRecordGroupSaved:
                  $ref: '#/components/examples/SingleRecordGroupSaved'
                singleRecordGroupRejected:
                  $ref: '#/components/examples/SingleRecordGroupRejected'
          description: >-
            Multi-status response with the list of statuses for each requested entity.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Problem'
          description: >
            Error response for cases when the backend rejects the attempt to add a new visit intention.
      operationId: createSeries
      tags:
        - Descriptions
  
  /descriptions:
    get:
      security:
        - jwt: []
      parameters:
        - in: query
          name: page
          description: Page number, zero if not sent
          required: false
          schema:
            type: integer
            minimum: 0
        - in: query
          name: q
          description: Search term
          required: false
          schema:
            type: string
            minLength: 3
            maxLength: 128
      operationId: getDescriptions
      tags:
        - Descriptions
      description: Returns a page of descriptions.
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MultiStatusResponse' # TODO
              examples:
                first:
                  $ref: '#/components/examples/RecordGroupsCreatedOk'
          description: >-
            A page of descriptions.

        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Problem'
          description: >-
            Error response indicating incorrect / inconsistent query parameters.
  /descriptions/advancement:
    put:
      security:
        - jwt: []
      operationId: advance
      tags:
        - Workflow Operations
      description: Advances descriptions from local to central office
      responses:
        '207':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MultiStatusResponse'
              examples:
                allOk:
                  $ref: '#/components/examples/RecordGroupsCreatedOk'
                partialSuccess:
                  $ref: '#/components/examples/RecordGroupsCreatedPartialSuccess'
          description: >-
            A list of resulting statuses for each requested item.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Problem'
          description: >-
            Error response indicating unauthorized access.


components:

  requestBodies:

    PostRecordGroupsRequest:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: models/RecordGroup.yaml
          examples:
            twoRecordGroupsToCreate:
              $ref: '#/components/examples/TwoRecordGroupsToCreate'
            singleRecordGroupToCreate:
              $ref: '#/components/examples/SingleRecordGroupToCreate'
            singleRecordGroupMissingRequiredField:
              $ref: '#/components/examples/SingleRecordGroupMissingRequiredField'
      description: > 
        A list of Record Group archival descriptions.

    PostCollectionsRequest:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: models/Collection.yaml
      description: > 
        A list of Collection archival descriptions.

    PostSeriesRequest:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: models/Series.yaml
      description: > 
        A list of Series archival descriptions.

  schemas:
        
    SeriesFileUnitAndItemDescriptionCommonProperties: 
      description: Parent object encapsulating 'Series', 'FileUnit' and 'Item' common properties
      type: object
      properties:
        title:
          description: > 
            <p>A title.</p> See additional guidelines on this field for <a href="https://www.archives.gov/research/catalog/lcdrg/elements/title.html#10">Series descriptions</a>, <a href="https://www.archives.gov/research/catalog/lcdrg/elements/title.html#18">FileUnit descriptions</a>, <a href="https://www.archives.gov/research/catalog/lcdrg/elements/title.html#19">Item descriptions</a>
          type: string
          example: "Triumph of the Will"
          minLength: 20
          maxLength: 700
        generalRecordsType:
          description: |
            <p>The general intellectual form of the archival materials.</p>
            <p><a href="https://www.archives.gov/research/catalog/lcdrg/elements/grt.html">See also</a></p>
          type: string
          example: "Photographs and other Graphic Materials"
          minLength: 1
          maxLength: 100
        accessRestrictionStatus:
          description: |
            <p><h1>TODO!!! This is the link to an Authority. Should this property be a string, or a complex object with the NAID??</h1></p>
            <p>The indication of whether or not there are access restrictions on the archival materials.</p>
            <p><a href="https://www.archives.gov/research/catalog/lcdrg/elements/access.html">See also</a></p>
            <p><a href="https://www.archives.gov/research/catalog/lcdrg/authority_lists/accesslist.html">Related Authority</a></p>
          type: string
          example: "Restricted - Partly"
          minLength: 1
          maxLength: 100
        specificAccess:
          type: array
          minItems: 1
          uniqueItems: true
          items:
            $ref: '#/components/schemas/SpecificAccessRestrictionWithSecurityClassification'
        useRestrictionStatus:
          description: |
            <p><h1>TODO!!! This is the link to an Authority. Should this property be a string, or a complex object with the NAID??</h1></p>
            <p>Indication of whether or not there are use restrictions on the archival materials.</p>
            <p><a href="https://www.archives.gov/research/catalog/lcdrg/elements/use.html">See also</a></p>
            <p><a href="https://www.archives.gov/research/catalog/lcdrg/authority_lists/uselist.html">Related Authority</a></p>
          type: string
          example: "Restricted - Possibly"
          minLength: 1
          maxLength: 25
        specificUseRestriction:
          description: |
            <p><h1>TODO!!! This is the link to an Authority. Should this property be a string, or a complex object with the NAID??</h1></p>
            <p>The identification of the type of use restrictions, based on copyright, donor, or statutory provisions, on the archival materials.</p>
            <p><a href="https://www.archives.gov/research/catalog/lcdrg/elements/specificuse.html">See also</a></p>
            <p><a href="https://www.archives.gov/research/catalog/lcdrg/authority_lists/specificuselist.html">Related Authority</a></p>
          type: string
          example: "Donor Restrictions"
          minLength: 1
          maxLength: 100
        inclusiveStartDate:
          type: string
          pattern: (0[1-9]|1[012])[/](0[1-9]|[12][0-9]|3[01])[/](17|18|19|20)\d\d
          description: >
            <a href="https://www.archives.gov/research/catalog/lcdrg/elements/inclusivestart.html">The beginning date</a> on which the record group, collection, series, or item was created, maintained, or accumulated by the creator.
        inclusiveEndDate:
          type: string
          pattern: (0[1-9]|1[012])[/](0[1-9]|[12][0-9]|3[01])[/](17|18|19|20)\d\d
          description: >
            <a href="https://www.archives.gov/research/catalog/lcdrg/elements/inclusivestart.html">The last date</a> on which the record group, collection, series, or item was created, maintained, or accumulated by the creator.
        creatingIndividual:
          description: |
            <p><h1>TODO!!! This is the link to an Authority. Should this property be a string, or a complex object with the NAID??</h1></p>
            <p>The name of a person responsible for the creation, accumulation, or maintenance of the series when in working (primary) use.</p>
            <p><a href="https://www.archives.gov/research/catalog/lcdrg/elements/specificuse.html">See also</a></p>
            <p><a href="https://www.archives.gov/research/catalog/lcdrg/authority_lists/specificuselist.html">Related Authority</a></p>
          type: string
          example: "Donor Restrictions"
          minLength: 1
          maxLength: 100
      required:
        - title
        - generalRecordsType
        - accessRestrictionStatus
        - specificAccessRestriction
        - securityClassification
        - useRestrictionStatus
        - specificUseRestriction
        - inclusiveStartDate
        - inclusiveEndDate

    Series:
      description: Series archival description. <a href="https://www.archives.gov/research/catalog/lcdrg/mandatoryelements.html#series">See mandatory properties list</a>
      type: object
      allOf:
        - $ref: '#/components/schemas/SeriesFileUnitAndItemDescriptionCommonProperties'
        - type: object
          properties:
            function:
              description: |
                <p>The description of why the archival materials were created.
    
                This element differs from Scope and Content Note, which describes the significant information contained within the records.
                
                Function and Use is about the activities that resulted in the creation of the archival materials.
                Scope and Content Note is what is in the archival materials.</p>
                <p><a href="https://www.archives.gov/research/catalog/lcdrg/elements/function.html">See also</a></p>
              type: string
              example: "The Reports of Death were created at field hospitals or by battlefield commanders and were later used by Sextons to complete Internment Records"
              minLength: 20
              maxLength: 2000
            inclusiveStartDate:
              type: string
              pattern: (0[1-9]|1[012])[/](0[1-9]|[12][0-9]|3[01])[/](17|18|19|20)\d\d
              description: >
                <a href="https://www.archives.gov/research/catalog/lcdrg/elements/inclusivestart.html">The beginning date</a> on which the record group, collection, series, or item was created, maintained, or accumulated by the creator.
            inclusiveEndDate:
              type: string
              pattern: (0[1-9]|1[012])[/](0[1-9]|[12][0-9]|3[01])[/](17|18|19|20)\d\d
              description: >
                <a href="https://www.archives.gov/research/catalog/lcdrg/elements/inclusivestart.html">The last date</a> on which the record group, collection, series, or item was created, maintained, or accumulated by the creator.
      required:
        - function

    SpecificAccessRestrictionWithSecurityClassification:
      description: | 
        <p><a href="https://www.archives.gov/research/catalog/lcdrg/elements/specificaccess.html">Specific Access Restriction</a> along with the <a href="https://www.archives.gov/research/catalog/lcdrg/elements/security.html">Security Classification</a></p>
      type: object
      properties:
        specificAccessRestriction:
          description: |
            <p><h1>TODO!!! This is the link to an Authority. Should this property be a string, or a complex object with the NAID??</h1></p>
            <p><h1>If a Restriction Status of "Restricted - Fully" or "Restricted - Partly" is selected, then the Specific Restriction becomes mandatory. If a Specific Access Restriction of "FOIA (b)(1) National Security", "Donated - Security Classified", or "Security Classified - Mandatory Review" is selected, then the Security Classification also becomes mandatory.</h1></p>
            <p>Specific access restrictions to the archival materials, based on national security considerations, donor restrictions, court orders, and other statutory or regulatory provisions.</p>
            <p><a href="https://www.archives.gov/research/catalog/lcdrg/elements/specificaccess.html">See also</a></p>
            <p><a href="https://www.archives.gov/research/catalog/lcdrg/authority_lists/specificaccesslist.html">Related Authority</a></p>
          type: string
          example: "PRMPA - National Security Classified (B)"
          minLength: 1
          maxLength: 100
        securityClassification:
          description: |
            <p><h1>TODO!!! This is the link to an Authority. Should this property be a string, or a complex object with the NAID??</h1></p>
            <p>The highest level of national security protections or classified nuclear information protections on the archival materials.</p>
            <p><a href="https://www.archives.gov/research/catalog/lcdrg/elements/security.html">See also</a></p>
            <p><a href="https://www.archives.gov/research/catalog/lcdrg/authority_lists/securitylist.html">Related Authority</a></p>
          type: string
          example: "Restricted Data/Formerly Restricted Data"
          minLength: 1
          maxLength: 40

    NaidStatusesResponse:
      description: Itemised report for a batch operation
      type: array
      items:
        allOf:
          - $ref: '#/components/schemas/Naid'
          - $ref: '#/components/schemas/OperationStatusCode'
        required:
          - naid
          - status
          
    Naid:
      description: NAID
      type: object
      properties:
        naid:
          description: NAID
          type: integer
          minimum: 0
          
    OperationStatusCode:
      type: object
      properties:
        status:
          type: number          
          enum:
            - 200
            - 201
            - 400
            - 401
            - 403
            - 404
            - 500

    MultiStatusResponse:
      type: array
      items:
        allOf:
          - $ref: '#/components/schemas/OperationStatusCode'
          - type: object
            properties:
              entityCode:
                type: string


  examples:

    RecordGroupsCreatedOk:
      value:
        - status: 201
          entityCode: "406"
        - status: 201
          entityCode: "721"

    RecordGroupsCreatedPartialSuccess:
      value:
        - status: 201
          entityCode: "406"
        - status: 400
          entityCode: "721"


    SingleCollection:
      value:
        naid: 63542091
        collectionIdentifier: "BHO-AC"
        title: "Barack Obama Artifact Collection"
        inclusiveStartDate: "01/20/2009"
        inclusiveEndDate: "01/20/2017"
        descriptionType: "collection"

    TwoRecordGroupsToCreate:
      value:
        - recordGroupNumber: 77
          title: "Records of the Office of the Chief of Engineers"
          inclusiveStartDate: "01/01/1789"
          inclusiveEndDate: "12/31/1999"
          descriptionType: "recordGroup"
        - recordGroupNumber: 432
          title: "Records of the Economic Stabilization Programs"
          inclusiveStartDate: "01/01/1971"
          inclusiveEndDate: "12/31/1974"
          descriptionType: "recordGroup"

    SingleRecordGroupToCreate:
      value:
        - recordGroupNumber: 77
          title: "Records of the Office of the Chief of Engineers"
          inclusiveStartDate: "01/01/1789"
          inclusiveEndDate: "12/31/1999"
          descriptionType: "recordGroup"

    SingleRecordGroupSaved:
      value:
        - status: 201
          entityCode: "406"
    
    SingleRecordGroupMissingRequiredField:
      value:
        - recordGroupNumber: 77
          inclusiveStartDate: "01/01/1789"
          inclusiveEndDate: "12/31/1999"
          descriptionType: "recordGroup"

    SingleRecordGroupRejected:
      value:
        - status: 400
          entityCode: "77"

  responses:
    Problem:
      description: error occurred - see status code and problem object for more information.
      content:
        'application/problem+json':
          schema:
            $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'

  securitySchemes:
    jwt:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
    basic:
      type: http
      description: Basic Authentication
      scheme: basic
security:
  - jwt: []
  - basic: []